---
title: "HeatmapExample"
author: "Anishka  Dhar"
date: "9/1/2021"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{heatmap example demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Introduction
Generate_heatmap example using the format from the help file with r-data set "morley"


```{r, echo=FALSE}
if (F) {
  ## Calling Bioconductor
  if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  BiocManager::install("marray")
  load("../data.RData")
}
```

``` {r}
library("marray")
```


```{r}
## Main numeric matrix
x <- as.matrix(morley)
## Column annotation df
set.seed(575)
anno_rows <- ncol(morley)
anno_columns <- 4
random_data <- rnorm(anno_rows*anno_columns)
annotation_df <- matrix(data = random_data, nrow = anno_rows, ncol = anno_columns)
colnames(annotation_df) <- c('C1', 'C2', 'C3','C4')
annotation_df <- as.data.frame(annotation_df)
```
```{r eval=FALSE}
generate_heatmap(x, row_anno = FALSE, col_anno = FALSE, col_info = FALSE, row_info = FALSE, row_dend = FALSE, col_dend = FALSE)
```
```{r eval=FALSE}
generate_heatmap(x, row_anno = FALSE, col_anno = FALSE, col_info = FALSE, row_info = FALSE, row_dend = FALSE, col_dend = TRUE)
```

```{r eval=FALSE}
generate_heatmap(x, row_anno = FALSE, col_anno = TRUE, col_info = column_df, row_info = FALSE, col_anno_var = c("C1"), row_anno_var = FALSE, row_dend = FALSE, col_dend = TRUE)
```

```{r eval=FALSE}
generate_heatmap(x, row_anno = FALSE, col_anno = TRUE, col_info = column_df, col_anno_var = c("C1", "C2", "C3", "C4"), row_dend = FALSE, col_dend = TRUE)
``` 
